import * as THREE from 'three';
import './style.css';

const $=id=>document.getElementById(id);
const ui={menu:$('menu'),settings:$('settings'),pause:$('pause'),end:$('endScreen'),hud:$('hud'),play:$('playBtn'),settingsBtn:$('settingsBtn'),settingsClose:$('settingsClose'),resume:$('resumeBtn'),quit:$('quitBtn'),retry:$('retryBtn'),endMenu:$('endMenuBtn'),quality:$('qualitySelect'),shake:$('shakeToggle'),audio:$('audioToggle'),crystals:$('crystalCount'),objective:$('objectiveText'),timer:$('timerText'),batteryText:$('batteryText'),batteryBar:$('batteryBar'),staminaBar:$('staminaBar'),healthText:$('healthText'),healthBar:$('healthBar'),prompt:$('prompt'),warning:$('warning'),minimap:$('minimap'),platform:$('platformTag'),endTitle:$('endTitle'),endText:$('endText'),endEyebrow:$('endEyebrow')};
ui.platform.textContent=window.templeDesktop?.desktop?`DESKTOP BUILD · ${window.templeDesktop.platform.toUpperCase()}`:'WEB BUILD';
ui.quality.value=localStorage.getItem('temple.quality')||'auto';
ui.shake.checked=localStorage.getItem('temple.shake')!=='0';
ui.audio.checked=localStorage.getItem('temple.audio')!=='0';

const PRESETS={legacy:{ratio:1,shadows:false,decor:.35},balanced:{ratio:1.25,shadows:true,decor:.6},high:{ratio:1.5,shadows:true,decor:.9}};
const preset=()=>PRESETS[ui.quality.value==='auto'?((navigator.hardwareConcurrency||4)<=4?'legacy':'balanced'):ui.quality.value];
const CELL=4,H=3.8,TOTAL=5,DIRS=[[-1,0,'n','s'],[1,0,'s','n'],[0,-1,'w','e'],[0,1,'e','w']];
let renderer,scene,camera,clock,maze,walls=[],crystalMeshes=[],trapCells=[],portal,portalLight,guardian,guardianCell,guardianPath=[],raf,state='menu',yaw=0,pitch=0,timeLeft=600,collected=0,elapsed=0,think=0;
const keys=new Set(),player={p:new THREE.Vector3(),vy:0,ground:true,health:100,stamina:100,battery:100,cool:0};
const mini=ui.minimap.getContext('2d');

let ctx,master,drone;
function audioStart(){if(!ui.audio.checked)return;if(!ctx){ctx=new AudioContext();master=ctx.createGain();master.gain.value=.25;master.connect(ctx.destination)}if(ctx.state==='suspended')ctx.resume();if(!drone){drone=ctx.createOscillator();const g=ctx.createGain();drone.frequency.value=46;g.gain.value=.08;drone.connect(g).connect(master);drone.start()}}
function tone(f,d=.15,g=.06,type='sine'){if(!ui.audio.checked)return;audioStart();const o=ctx.createOscillator(),v=ctx.createGain();o.type=type;o.frequency.value=f;v.gain.setValueAtTime(g,ctx.currentTime);v.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.connect(v).connect(master);o.start();o.stop(ctx.currentTime+d)}
function sfx(kind){if(kind==='crystal'){tone(550,.18,.07);setTimeout(()=>tone(900,.25,.05),70)}else if(kind==='threat'){tone(58,.45,.09,'sawtooth')}else if(kind==='portal'){tone(92,.7,.08);tone(360,.7,.035,'triangle')}else tone(120,.04,.018,'square')}

function makeMaze(n=9){const g=Array.from({length:n},(_,r)=>Array.from({length:n},(_,c)=>({r,c,n:true,s:true,e:true,w:true,v:false})));const st=[g[0][0]];g[0][0].v=true;while(st.length){const a=st.at(-1),opts=DIRS.map(d=>({d,r:a.r+d[0],c:a.c+d[1]})).filter(x=>x.r>=0&&x.c>=0&&x.r<n&&x.c<n&&!g[x.r][x.c].v);if(!opts.length){st.pop();continue}const x=opts[(Math.random()*opts.length)|0],b=g[x.r][x.c];a[x.d[2]]=false;b[x.d[3]]=false;b.v=true;st.push(b)}g.flat().forEach(c=>delete c.v);return g}
function wpos(c,y=0){return new THREE.Vector3((c.c-(maze.length-1)/2)*CELL,y,(c.r-(maze.length-1)/2)*CELL)}
function cellAt(p){const c=Math.max(0,Math.min(maze.length-1,Math.round(p.x/CELL+(maze.length-1)/2))),r=Math.max(0,Math.min(maze.length-1,Math.round(p.z/CELL+(maze.length-1)/2)));return maze[r][c]}
function farthest(start){const q=[start],dist=new Map([[`${start.r},${start.c}`,0]]);let best=start;while(q.length){const a=q.shift(),ad=dist.get(`${a.r},${a.c}`);if(ad>dist.get(`${best.r},${best.c}`))best=a;for(const d of DIRS){if(a[d[2]])continue;const r=a.r+d[0],c=a.c+d[1],k=`${r},${c}`;if(!dist.has(k)){dist.set(k,ad+1);q.push(maze[r][c])}}}return best}
function path(a,b){const q=[a],seen=new Set([`${a.r},${a.c}`]),prev=new Map();while(q.length){const x=q.shift();if(x===b)break;for(const d of DIRS){if(x[d[2]])continue;const r=x.r+d[0],c=x.c+d[1],k=`${r},${c}`;if(!seen.has(k)){seen.add(k);prev.set(k,x);q.push(maze[r][c])}}}const out=[];for(let x=b;x&&x!==a;x=prev.get(`${x.r},${x.c}`))out.push(x);return out.reverse()}
function randomCells(n,ban=[]){const bad=new Set(ban.map(x=>`${x.r},${x.c}`)),a=maze.flat().filter(x=>!bad.has(`${x.r},${x.c}`));for(let i=a.length-1;i;i--){const j=(Math.random()*(i+1))|0;[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,n)}
function material(c,e=0,ei=0){return new THREE.MeshStandardMaterial({color:c,roughness:.95,metalness:.03,emissive:e,emissiveIntensity:ei})}
function box(x,y,z,w,h,d,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;scene.add(o);walls.push({x1:x-w/2,x2:x+w/2,z1:z-d/2,z2:z+d/2})}

function build(){
 maze=makeMaze();walls=[];crystalMeshes=[];const spawn=maze[0][0],exit=farthest(spawn),q=preset();scene=new THREE.Scene();scene.background=new THREE.Color(0x02080a);scene.fog=new THREE.FogExp2(0x041114,.048);camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.08,70);camera.rotation.order='YXZ';renderer=new THREE.WebGLRenderer({antialias:q.shadows,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,q.ratio));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=q.shadows;$('game').replaceChildren(renderer.domElement);clock=new THREE.Clock();
 scene.add(new THREE.HemisphereLight(0x315b60,0x030506,.55));const sun=new THREE.DirectionalLight(0x8ab8bf,.28);sun.position.set(4,8,-4);scene.add(sun);const flash=new THREE.SpotLight(0xf5fff4,5,18,Math.PI/8,.5,1.5),target=new THREE.Object3D();target.position.z=-6;camera.add(flash,target);flash.target=target;scene.add(camera);camera.userData.flash=flash;
 const stone=material(0x182728),floor=material(0x0d1718);const fl=new THREE.Mesh(new THREE.PlaneGeometry(maze.length*CELL+4,maze.length*CELL+4),floor);fl.rotation.x=-Math.PI/2;scene.add(fl);
 maze.flat().forEach(c=>{const p=wpos(c);if(c.n)box(p.x,H/2,p.z-CELL/2,CELL+.3,H,.3,stone);if(c.w)box(p.x-CELL/2,H/2,p.z,.3,H,CELL+.3,stone);if(c.r===maze.length-1&&c.s)box(p.x,H/2,p.z+CELL/2,CELL+.3,H,.3,stone);if(c.c===maze.length-1&&c.e)box(p.x+CELL/2,H/2,p.z,.3,H,CELL+.3,stone)});
 const decor=material(0x38d7d0,0x22bdb7,2);randomCells(Math.floor(maze.length*maze.length*q.decor),[spawn,exit]).forEach(c=>{const p=wpos(c);const o=new THREE.Mesh(new THREE.OctahedronGeometry(.12),decor);o.scale.y=2.4;o.position.set(p.x+(Math.random()-.5)*2.5,.25,p.z+(Math.random()-.5)*2.5);scene.add(o)});
 const picks=randomCells(TOTAL,[spawn,exit]);picks.forEach((c,i)=>{const o=new THREE.Mesh(new THREE.OctahedronGeometry(.35),material(0x7afff8,0x2feee5,3));o.position.copy(wpos(c,.6));o.userData={cell:c,active:true,phase:i};scene.add(o);crystalMeshes.push(o)});trapCells=randomCells(5,[spawn,exit,...picks]);
 trapCells.forEach(c=>{const p=wpos(c);for(let i=-1;i<=1;i++){const o=new THREE.Mesh(new THREE.ConeGeometry(.11,.45,5),material(0x354345));o.position.set(p.x+i*.4,.22,p.z);scene.add(o)}});
 portal=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(1.1,.18,8,32),material(0x163435,0x1fd3ca,.2));ring.rotation.y=Math.PI/2;portal.add(ring);portal.position.copy(wpos(exit,1.45));scene.add(portal);portal.userData.exit=exit;portalLight=new THREE.PointLight(0x42f4eb,0,7);portalLight.position.copy(portal.position);scene.add(portalLight);
 guardianCell=farthest(exit);guardian=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(1,1.45,.6),material(0x202b2b));body.position.y=1.2;guardian.add(body);const head=new THREE.Mesh(new THREE.DodecahedronGeometry(.45),material(0x0a1011));head.position.y=2.1;guardian.add(head);for(const s of [-1,1]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.07,8,8),material(0x7afff8,0x34eee5,4));eye.position.set(.15*s,2.15,-.42);guardian.add(eye)}guardian.position.copy(wpos(guardianCell));guardian.visible=false;scene.add(guardian);
 player.p.copy(wpos(spawn,1.65));player.health=player.stamina=player.battery=100;player.vy=0;player.ground=true;player.cool=0;collected=elapsed=0;timeLeft=600;guardianPath=[];think=0;yaw=pitch=0;ui.objective.textContent='Find the five gate crystals';updateHud();
}
function hit(x,z){const r=.33;return walls.some(w=>x+r>w.x1&&x-r<w.x2&&z+r>w.z1&&z-r<w.z2)}
function move(dt){const f=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),s=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),m=f||s,run=keys.has('ShiftLeft')&&m&&player.stamina>12,spd=run?4.7:2.8;if(m){const l=Math.hypot(f,s),dx=(-Math.sin(yaw)*f/l+Math.cos(yaw)*s/l)*spd*dt,dz=(-Math.cos(yaw)*f/l-Math.sin(yaw)*s/l)*spd*dt;if(!hit(player.p.x+dx,player.p.z))player.p.x+=dx;if(!hit(player.p.x,player.p.z+dz))player.p.z+=dz;if(run)player.stamina=Math.max(0,player.stamina-24*dt)}else player.stamina=Math.min(100,player.stamina+18*dt);player.vy-=16*dt;player.p.y+=player.vy*dt;if(player.p.y<=1.65){player.p.y=1.65;player.vy=0;player.ground=true}camera.position.copy(player.p);camera.rotation.set(pitch,yaw,0,'YXZ')}
function nearest(){let best=null,d=99;for(const c of crystalMeshes)if(c.userData.active){const x=c.position.distanceTo(player.p);if(x<d){d=x;best=c}}return d<1.4?best:null}
function take(c){c.userData.active=false;c.visible=false;collected++;sfx('crystal');if(collected===TOTAL){portalLight.intensity=2.3;portal.children[0].material.emissiveIntensity=3;ui.objective.textContent='Reach the awakened gate';sfx('portal')}updateHud()}
function guardianTick(dt){if(elapsed<14)return;guardian.visible=true;const pc=cellAt(player.p),d=guardian.position.distanceTo(player.p);think-=dt;if(think<=0){guardianPath=path(guardianCell,pc);think=d<9?.3:1}if(guardianPath.length){const next=guardianPath[0],t=wpos(next),v=t.clone().sub(guardian.position);v.y=0;if(v.length()<.13){guardianCell=next;guardianPath.shift()}else{v.normalize();guardian.position.addScaledVector(v,(d<9?2.3:1.4)*dt);guardian.rotation.y=Math.atan2(v.x,v.z)}}ui.warning.classList.toggle('hidden',d>7);if(d<1.15&&player.cool<=0){player.health-=22;player.cool=1.4;sfx('threat');if(player.health<=0)finish(false,'The Guardian found you.')}}
function updateHud(){ui.crystals.textContent=`${collected}/${TOTAL}`;ui.healthText.textContent=Math.max(0,Math.ceil(player.health));ui.healthBar.style.width=`${Math.max(0,player.health)}%`;ui.staminaBar.style.width=`${player.stamina}%`;ui.batteryText.textContent=`${Math.ceil(player.battery)}%`;ui.batteryBar.style.width=`${player.battery}%`}
function map(){mini.clearRect(0,0,180,180);mini.fillStyle='rgba(0,9,11,.88)';mini.beginPath();mini.arc(90,90,88,0,7);mini.fill();const pc=cellAt(player.p),sc=17;mini.strokeStyle='rgba(150,230,225,.16)';maze.flat().forEach(c=>{const x=90+(c.c-pc.c)*sc,y=90+(c.r-pc.r)*sc;if(c.n){mini.beginPath();mini.moveTo(x-sc/2,y-sc/2);mini.lineTo(x+sc/2,y-sc/2);mini.stroke()}if(c.w){mini.beginPath();mini.moveTo(x-sc/2,y-sc/2);mini.lineTo(x-sc/2,y+sc/2);mini.stroke()}});for(const c of crystalMeshes)if(c.userData.active){mini.fillStyle='#55eee6';mini.beginPath();mini.arc(90+(c.userData.cell.c-pc.c)*sc,90+(c.userData.cell.r-pc.r)*sc,2.5,0,7);mini.fill()}mini.save();mini.translate(90,90);mini.rotate(-yaw);mini.fillStyle='#fff';mini.beginPath();mini.moveTo(0,-7);mini.lineTo(5,6);mini.lineTo(-5,6);mini.fill();mini.restore()}
function tick(){if(state!=='playing')return;raf=requestAnimationFrame(tick);const dt=Math.min(.04,clock.getDelta());elapsed+=dt;timeLeft-=dt;player.cool=Math.max(0,player.cool-dt);move(dt);player.battery=Math.max(0,player.battery-dt*.65);camera.userData.flash.intensity=player.battery?5:0;const cell=cellAt(player.p);if(player.cool<=0&&trapCells.includes(cell)){player.health-=14;player.cool=1.2;if(player.health<=0)finish(false,'The temple claimed you.')}guardianTick(dt);crystalMeshes.forEach(c=>{if(c.userData.active){c.rotation.y+=dt;c.position.y=.6+Math.sin(elapsed*2+c.userData.phase)*.08}});if(collected===TOTAL&&player.p.distanceTo(portal.position)<1.2)finish(true);const sec=Math.max(0,Math.ceil(timeLeft));ui.timer.textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;if(sec<=0)finish(false,'The gate sealed before you escaped.');ui.prompt.classList.toggle('hidden',!nearest());updateHud();map();renderer.render(scene,camera)}
function start(){audioStart();build();state='playing';ui.menu.classList.add('hidden');ui.end.classList.add('hidden');ui.hud.classList.remove('hidden');renderer.domElement.requestPointerLock?.();clock.start();tick()}
function pause(){if(state!=='playing')return;state='paused';cancelAnimationFrame(raf);ui.pause.classList.remove('hidden');document.exitPointerLock?.()}
function resume(){if(state!=='paused')return;state='playing';ui.pause.classList.add('hidden');renderer.domElement.requestPointerLock?.();clock.getDelta();tick()}
function menu(){state='menu';cancelAnimationFrame(raf);document.exitPointerLock?.();ui.pause.classList.add('hidden');ui.end.classList.add('hidden');ui.hud.classList.add('hidden');ui.menu.classList.remove('hidden')}
function finish(win,msg){state='ended';cancelAnimationFrame(raf);document.exitPointerLock?.();ui.hud.classList.add('hidden');ui.end.classList.remove('hidden');ui.endEyebrow.textContent=win?'THE FORGOTTEN GATE':'THE TEMPLE';ui.endTitle.textContent=win?'ESCAPED':'LOST';ui.endText.textContent=msg||(win?'The gate opens. You made it out.':'You did not escape.');sfx(win?'portal':'threat')}

ui.play.onclick=start;ui.retry.onclick=start;ui.settingsBtn.onclick=()=>ui.settings.classList.remove('hidden');ui.settingsClose.onclick=()=>{ui.settings.classList.add('hidden');localStorage.setItem('temple.quality',ui.quality.value);localStorage.setItem('temple.shake',ui.shake.checked?'1':'0');localStorage.setItem('temple.audio',ui.audio.checked?'1':'0')};ui.resume.onclick=resume;ui.quit.onclick=menu;ui.endMenu.onclick=menu;
addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space'&&state==='playing'&&player.ground){player.vy=5.2;player.ground=false}if(e.code==='KeyE'&&state==='playing'){const c=nearest();if(c)take(c)}if(e.code==='Escape'&&state==='playing')pause()});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('mousemove',e=>{if(state!=='playing'||document.pointerLockElement!==renderer?.domElement)return;yaw-=e.movementX*.0021;pitch=Math.max(-1.4,Math.min(1.4,pitch-e.movementY*.0019))});document.addEventListener('pointerlockchange',()=>{if(state==='playing'&&document.pointerLockElement!==renderer?.domElement)pause()});addEventListener('resize',()=>{if(!camera||!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
